# Generated by Django 2.2 on 2019-06-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('magic_abilities', models.TextField(max_length=250)),
                ('dangers', models.TextField(max_length=250)),
                ('habitat', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
