# Generated by Django 2.2 on 2019-06-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190612_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='beast',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
