# Generated by Django 2.2 on 2019-06-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_beast_toys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('beast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Beast')),
            ],
        ),
    ]
